version: '3'

services:
  api:
    container_name: api # Name can be anything
    restart: always
    build: ./api
    ports:
      - "8050:5000"
    command: gunicorn -w 1 -b :5000 app:app
  nginx:
    container_name: server_nginx
    restart: always
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api